# Generated by Django 4.1.2 on 2022-10-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('category', models.CharField(max_length=128, null=True)),
                ('states', models.CharField(max_length=128, null=True)),
                ('iso', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('category', models.CharField(max_length=128, null=True)),
                ('iso', models.CharField(max_length=128, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.region')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('justification', models.CharField(max_length=128, null=True)),
                ('year', models.IntegerField(null=True)),
                ('longitude', models.CharField(max_length=128, null=True)),
                ('latitude', models.CharField(max_length=128, null=True)),
                ('area_hectares', models.CharField(max_length=128, null=True)),
                ('region', models.CharField(max_length=128, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.category')),
                ('iso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.iso')),
                ('states', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.state')),
            ],
        ),
    ]
